spring:
  # H2 Database settings
  h2.console.enabled: true
  data.jpa.repositories.bootstrap-mode: default
  datasource:
    url: jdbc:h2:mem:testdb
    data: classpath:init-data.sql
    driver-class-name: org.h2.Driver